### ISSUE TITLE
DHCPv4 sockets seem to cause an assertion failure

### ISSUE THREAD

**Issue by veluca93** [smoltcp-rs/smoltcp#716] opened 2022-12-11 01:19 UTC
Hi!
This is the first time I am trying to use `smoltcp`, so it is entirely possible I am doing something wrong.
I have been trying to add a DHCP socket to an Ethernet interface; as soon as I do that, the second call to poll() results in an assertion failure.

Here is a reduced source file that reproduces the issue (with smoltcp v0.8.2):
```
use std::collections::BTreeMap;

use log::info;
use smoltcp::{
    iface::{InterfaceBuilder, NeighborCache, Routes},
    phy::{Device, DeviceCapabilities, Medium, RxToken, TxToken},
    socket::Dhcpv4Socket,
    time::Instant,
    wire::HardwareAddress,
    Result,
};

struct FakeDevice {}

const PACKET_SIZE: usize = 1514;

struct FakeRxToken {
    packet: [u8; PACKET_SIZE],
    len: usize,
}

struct FakeTxToken {}

impl TxToken for FakeTxToken {
    fn consume<R, F>(self, _: Instant, len: usize, f: F) -> Result<R>
    where
        F: FnOnce(&mut [u8]) -> Result<R>,
    {
        let mut buf = [0u8; PACKET_SIZE];
        assert!(len <= PACKET_SIZE);
        let payload = &mut buf[..len];

        let ret = f(payload)?;

        info!("transmit: {:?}", payload);

        Ok(ret)
    }
}

impl RxToken for FakeRxToken {
    fn consume<R, F>(mut self, _: Instant, f: F) -> Result<R>
    where
        F: FnOnce(&mut [u8]) -> Result<R>,
    {
        let packet = &mut self.packet[..self.len];
        info!("receive: {:?}", packet);
        f(packet)
    }
}

impl<'d> Device<'d> for FakeDevice {
    type TxToken = FakeTxToken;
    type RxToken = FakeRxToken;

    fn receive(&'d mut self) -> Option<(Self::RxToken, Self::TxToken)> {
        None
    }

    fn transmit(&'d mut self) -> Option<Self::TxToken> {
        Some(FakeTxToken {})
    }

    fn capabilities(&self) -> DeviceCapabilities {
        let mut caps = DeviceCapabilities::default();
        caps.medium = Medium::Ethernet;
        caps.max_transmission_unit = PACKET_SIZE;
        caps.max_burst_size = Some(1);
        caps
    }
}

fn main() {
    env_logger::init();
    let device = FakeDevice {};

    let routes = Routes::new(BTreeMap::new());
    let neighbor_cache = NeighborCache::new(BTreeMap::new());
    let hw_addr = HardwareAddress::Ethernet(smoltcp::wire::EthernetAddress::from_bytes(&[
        0, 1, 2, 3, 4, 5,
    ]));

    let mut interface = InterfaceBuilder::new(device, Vec::new())
        .hardware_addr(hw_addr)
        .routes(routes)
        .neighbor_cache(neighbor_cache)
        .finalize();

    let dhcp_socket = Dhcpv4Socket::new();
    let dhcp_socket_handle = interface.add_socket(dhcp_socket);

    for i in 0.. {
        info!("IPs: {:?}", interface.ip_addrs());
        let status = interface.poll(Instant::from_micros(i));
        info!("Poll: {:?}", status);

        let dhcp_status = interface
            .get_socket::<Dhcpv4Socket>(dhcp_socket_handle)
            .poll();

        info!("{:?}", dhcp_status);
    }
}
```

and here are the corresponding logs:

```
luca@xps ~/smoltcp-repro  $ RUST_LOG=trace cargo run
   Compiling smoltcp-repro v0.1.0 (/home/luca/smoltcp-repro)
    Finished dev [unoptimized + debuginfo] target(s) in 0.49s
     Running `target/debug/smoltcp-repro`
[2022-12-11T01:03:38Z TRACE smoltcp::iface::socket_set] [0]: adding
[2022-12-11T01:03:38Z INFO  smoltcp_repro] IPs: []
[2022-12-11T01:03:38Z DEBUG smoltcp::socket::dhcpv4] DHCP send DISCOVER to 255.255.255.255: Repr { message_type: Discover, transaction_id: 4260165794, client_hardware_address: Address([0, 1, 2, 3, 4, 5]), client_ip: Address([0, 0, 0, 0]), your_ip: Address([0, 0, 0, 0]), server_ip: Address([0, 0, 0, 0]), router: None, subnet_mask: None, relay_agent_ip: Address([0, 0, 0, 0]), broadcast: false, requested_ip: None, client_identifier: Some(Address([0, 1, 2, 3, 4, 5])), server_identifier: None, parameter_request_list: Some([1, 3, 6]), dns_servers: None, max_size: Some(1432), lease_duration: None }
[2022-12-11T01:03:38Z TRACE smoltcp::iface::socket_meta] #0: neighbor 255.255.255.255 missing, silencing until t+3.000s
[2022-12-11T01:03:38Z INFO  smoltcp_repro] Poll: Ok(false)
[2022-12-11T01:03:38Z INFO  smoltcp_repro] Some(Deconfigured)
[2022-12-11T01:03:38Z INFO  smoltcp_repro] IPs: []
thread 'main' panicked at 'assertion failed: protocol_addr.is_unicast()', /home/luca/.cargo/registry/src/github.com-1ecc6299db9ec823/smoltcp-0.8.2/src/iface/neighbor.rs:199:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Any help would be appreciated!

Note that the problem seems to go away if using current GitHub main:

```
use std::collections::BTreeMap;

use log::info;
use smoltcp::{
    iface::{InterfaceBuilder, NeighborCache, Routes, SocketSet},
    phy::{Device, DeviceCapabilities, Medium, RxToken, TxToken},
    socket::dhcpv4::Socket as Dhcpv4Socket,
    time::Instant,
    wire::HardwareAddress,
    Result,
};

struct FakeDevice {}

const PACKET_SIZE: usize = 1514;

struct FakeRxToken {
    packet: [u8; PACKET_SIZE],
    len: usize,
}

struct FakeTxToken {}

impl TxToken for FakeTxToken {
    fn consume<R, F>(self, _: Instant, len: usize, f: F) -> Result<R>
    where
        F: FnOnce(&mut [u8]) -> Result<R>,
    {
        let mut buf = [0u8; PACKET_SIZE];
        assert!(len <= PACKET_SIZE);
        let payload = &mut buf[..len];

        let ret = f(payload)?;

        info!("transmit: {:?}", payload);

        Ok(ret)
    }
}

impl RxToken for FakeRxToken {
    fn consume<R, F>(mut self, _: Instant, f: F) -> Result<R>
    where
        F: FnOnce(&mut [u8]) -> Result<R>,
    {
        let packet = &mut self.packet[..self.len];
        info!("receive: {:?}", packet);
        f(packet)
    }
}

impl Device for FakeDevice {
    type TxToken<'d> = FakeTxToken;
    type RxToken<'d> = FakeRxToken;

    fn receive(&mut self) -> Option<(Self::RxToken<'_>, Self::TxToken<'_>)> {
        None
    }

    fn transmit(&mut self) -> Option<Self::TxToken<'_>> {
        Some(FakeTxToken {})
    }

    fn capabilities(&self) -> DeviceCapabilities {
        let mut caps = DeviceCapabilities::default();
        caps.medium = Medium::Ethernet;
        caps.max_transmission_unit = PACKET_SIZE;
        caps.max_burst_size = Some(1);
        caps
    }
}

fn main() {
    env_logger::init();
    let mut device = FakeDevice {};

    let routes = Routes::new(BTreeMap::new());
    let neighbor_cache = NeighborCache::new(BTreeMap::new());
    let hw_addr = HardwareAddress::Ethernet(smoltcp::wire::EthernetAddress::from_bytes(&[
        0, 1, 2, 3, 4, 5,
    ]));

    let mut interface = InterfaceBuilder::new()
        .hardware_addr(hw_addr)
        .routes(routes)
        .neighbor_cache(neighbor_cache)
        .finalize(&mut device);

    let dhcp_socket = Dhcpv4Socket::new();
    let mut socket_set = SocketSet::new(vec![]);
    let dhcp_socket_handle = socket_set.add(dhcp_socket);

    for i in 0.. {
        info!("IPs: {:?}", interface.ip_addrs());
        let status = interface.poll(Instant::from_micros(i), &mut device, &mut socket_set);
        info!("Poll: {:?}", status);

        let dhcp_status = socket_set
            .get_mut::<Dhcpv4Socket>(dhcp_socket_handle)
            .poll();

        info!("{:?}", dhcp_status);
    }
}
```

**Comment by Dirbaio** [comment] 2023-01-15 22:25
Yes, this is a bug in v0.8.x. It's caused by having zero IPs. As a workaround, set the IP to `0.0.0.0/0` then change it to the real one when DHCP finishes. See the [example](https://github.com/smoltcp-rs/smoltcp/blob/v0.8.x/examples/dhcp_client.rs#L32).

It's fixed in master, and I won't fix it in v0.8.x since the fix is very nontrivial.

(technical details of the bug: It's the combination of `IpRepr::lower()` [returning Unaddressable](https://github.com/smoltcp-rs/smoltcp/blob/v0.8.2/src/wire/ip.rs#L638) because src IP is unspecified (`0.0.0.0`) and we have no IPv4 addrs, and then `socket_egress` [incorrectly treating all Unaddressable as "missing neighbor"](https://github.com/smoltcp-rs/smoltcp/blob/v0.8.2/src/iface/interface.rs#L945) which sets the socket to wait for the `255.255.255.255` neighbor. Then next poll fails because `255.255.255.255` is not unicast. It's fixed in git master because `lower` doesn't exist anymore, the interface code doesn't try to "resolve" `0.0.0.0` src addrs.)

**Closed as completed by Dirbaio** 2023-01-15 22:25 UTC
